### ISSUE TITLE
Error when opening map

### ISSUE THREAD

**Issue by AcesGamingUK** [codengine/SOTFEdit#16]
<details>
<summary> Error </summary>
<pre>
Version: 0.11.10
Message: Cannot locate resource 'images/structures/deerhide_tn.png'.
Exception Type: System.IO.IOException
Callstack:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart, FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at SOTFEdit.Infrastructure.AppLocalImageCache.LoadLocalImage(CacheKey cacheKey) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Infrastructure\AppLocalImageCache.cs:line 32
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at SOTFEdit.Infrastructure.AppLocalImageCache.Get(String pathRelativeToRoot, Nullable`1 width, Nullable`1 height) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Infrastructure\AppLocalImageCache.cs:line 13
   at SOTFEdit.Infrastructure.StringExtensions.LoadAppLocalImage(String pathRelativeToRoot, Nullable`1 width, Nullable`1 height) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Infrastructure\StringExtensions.cs:line 10
   at SOTFEdit.Model.Map.StructurePoi.get_Icon() in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Model\Map\StructurePoi.cs:line 17
   at SOTFEdit.ViewModel.MainViewModel.<>c.<OpenMap>b__72_0(KeyValuePair`2 kvp) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\ViewModel\MainViewModel.cs:line 541
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at SOTFEdit.ViewModel.MainViewModel.OpenMap() in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\ViewModel\MainViewModel.cs:line 540
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Inner Exception: 
</details>

**Comment by Mortennif** [comment]
From what I can see the deer hide icon is missing in the files. Can you remove it from your world and try again?

**Comment by codengine** [comment]
Thanks for the report, will be fixed in v0.11.11 which is currently in release
