### ISSUE TITLE
Error when choosing save

### ISSUE THREAD

**Issue by Moheior** [codengine/SOTFEdit#27]
when i try to choose my multiplayer save i get this error
 Version: 0.12.0
Message: Unexpected character encountered while parsing number: z. Path 'Actors[2072].Position.y', line 1, position 581159.
Exception Type: Newtonsoft.Json.JsonReaderException
Callstack:    at Newtonsoft.Json.JsonTextReader.ReadNumberCharIntoBuffer(Char currentChar, Int32 charPos)
   at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json)
   at SOTFEdit.Infrastructure.JsonConverter.DeserializeRaw(String json) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Infrastructure\JsonConverter.cs:line 48
   at SOTFEdit.Model.Savegame.SaveDataWrapper.Deserialize(JToken token) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Model\Savegame\SaveDataWrapper.cs:line 88
   at SOTFEdit.Model.Savegame.SaveDataWrapper.GetJsonBasedToken(String selector) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Model\Savegame\SaveDataWrapper.cs:line 37
   at SOTFEdit.ViewModel.NpcsPageViewModel.LoadNpcs(Savegame savegame) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\ViewModel\NpcsPageViewModel.cs:line 89
   at SOTFEdit.ViewModel.NpcsPageViewModel.Reload(Savegame selectedSavegame) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\ViewModel\NpcsPageViewModel.cs:line 71
   at SOTFEdit.ViewModel.NpcsPageViewModel.OnSelectedSavegameChanged(SelectedSavegameChangedEvent m) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\ViewModel\NpcsPageViewModel.cs:line 62
   at SOTFEdit.ViewModel.NpcsPageViewModel.<SetupListeners>b__15_0(Object _, SelectedSavegameChangedEvent m) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\ViewModel\NpcsPageViewModel.cs:line 45
   at CommunityToolkit.Mvvm.Messaging.Internals.MessageHandlerDispatcher.For`2.Invoke(Object recipient, Object message)
   at CommunityToolkit.Mvvm.Messaging.WeakReferenceMessenger.SendAll[TMessage](ReadOnlySpan`1 pairs, Int32 i, TMessage message)
   at CommunityToolkit.Mvvm.Messaging.WeakReferenceMessenger.Send[TMessage,TToken](TMessage message, TToken token)
   at CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.Send[TMessage](IMessenger messenger, TMessage message)
   at SOTFEdit.SavegameManager.set_SelectedSavegame(Savegame value) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\SavegameManager.cs:line 25
   at SOTFEdit.ViewModel.SelectSavegameViewModel.SelectSavegame(Savegame savegame) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\ViewModel\SelectSavegameViewModel.cs:line 40
   at CommunityToolkit.Mvvm.Input.RelayCommand`1.Execute(Object parameter)
   at SOTFEdit.Infrastructure.ItemDoubleClickBehavior.<OnAttached>b__1_0(Object _, MouseButtonEventArgs e) in D:\a\SOTFEdit\SOTFEdit\SOTFEdit\Infrastructure\ItemDoubleClickBehaviour.cs:line 51
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Control.OnPreviewMouseDoubleClick(MouseButtonEventArgs e)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Inner Exception:

**Comment by codengine** [comment]
Hi, did you modify the savegame externally?

**Comment by codengine** [comment]
Closed due to no response.
